### ISSUE TITLE
[feature] repo 명령어 작업

### ISSUE THREAD

**Issue by Hanjunhee-1** [EdgeCrafters/ejp-s#5]
# 요구사항
- repo 명령어에 대한 세부 명령어 작업을 해야합니다.

# Todo List
- [x] `show` 명령어 작업
- [x] `get` 명령어 작업
- [x] `clean` 명령어 작업

**Comment by Hanjunhee-1** [comment]
작업 완료하여 issue close 합니다
