### ISSUE TITLE
[feature] problem 명령어 작업

### ISSUE THREAD

**Issue by Hanjunhee-1** [EdgeCrafters/ejp-s#6]
# 요구사항
problem 명령어에 대한 세부 명령어 작업을 해야합니다.

# Todo List
- [x] `show`: `myRepos` 에 존재하는 repo 중에서 사용자가 보고 싶어하는 problem 에 대한 정보를 보여줍니다.
- [x] `test`: 문제에 대한 testcase 들이 존재한다면 사용자가 테스트 해보고 싶어하는 testcase 정보를 받아 해당 정보를 토대로 test 를 해주고 결과를 알려줍니다. test 할 파일의 위치 같은 것들은 사용자에게 직접 입력받습니다.
- [x] `submit`: 문제의 정답을 제출합니다. sha256 을 사용하여 복호화한 뒤에 ejs-be 로 요청을 보내줍니다. 정답 여부는 알수없습니다.
- [x] `testcase`: 문제의 테스트케이스 정보들을 출력합니다.
