### ISSUE TITLE
[fix] ejp-s

### ISSUE THREAD

**Issue by Hanjunhee-1** [EdgeCrafters/ejp-s#8]
# 요구 사항
고칠 것이 많습니다. http 통신 부분이 불안정하기 때문에 로직을 수정해야 합니다.

# Todo List
- [x] 프로젝트 이름 바꾸기 (`ejp-s` 로 바꿔주기. cache 폴더가 저장되는 .ejs 폴더 이름도 바꿔 줄수 있도록...)
- [x] hidden 테스트케이스는 로컬에서 테스트가 불가능하도록 하기
- [x] http 통신 부분 수정하기 (기존에는 `CURLOPT_WRITEFUNCTION` 에서 사용하는 콜백 함수에서 모든 것을 해결했는데 이 부분이 매우 불안정함. 정상적으로 작동하기도 하지만 안 되는 때가 더 많음.)
- [x] docker 컴포즈 파일 수정하기 (network_mode 를 host 로 수정해서 컨테이너끼리도 통신이 가능하도록 하기)
